### ISSUE TITLE
local variable 'IS_LOGGED' referenced before assignment

### ISSUE THREAD

**Issue by User195** [Blackwave-rt/pikabu#7]
#Бот все ещё работает?
Только что попробовал, зарегил акк и выполнил:
```
import pikabu
pika_api = pikabu.Api(login='мой логин', password='мой пасс')
pika_api.users.get("admin", "rating")
```

при выполении `pika_api.users.get("admin", "rating")` ошибка 
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/pikabu.py", line 568, in get
    return self.rating(login)
  File "/usr/local/lib/python2.7/dist-packages/pikabu.py", line 596, in rating
    _page = self.request("profile/" + login)
  File "/usr/local/lib/python2.7/dist-packages/pikabu.py", line 137, in request
    return fetch_url(url, self.settings, data, method, need_auth)
  File "/usr/local/lib/python2.7/dist-packages/pikabu.py", line 80, in fetch_url
    if need_auth and not IS_LOGGED:
UnboundLocalError: local variable 'IS_LOGGED' referenced before assignment
```

**Comment by zoldaten** [comment]
IS_LOGGED должна появиться в области видимости функции.

Короче, вот надо добавить:
было:
if need_auth and not IS_LOGGED:

стало: 
global IS_LOGGED
    if need_auth and not IS_LOGGED:
